
version: '3'
volumes:
  postgres-db:
    driver: local
  maria-db:
    driver: local
  mssql-db:
    driver: local
  oracle-db:
    driver: local
  # mysql-db:
  #   mysql: local
networks:
  postgres-network:
    driver: bridge
  mssql-network:
    driver: bridge
  mysql-network:
    driver: bridge
  maria-network:
    driver: bridge
  oracle-network:
    driver: bridge

services:

# -- MSSQL SERVICE --
  rdb_mssql:
    container_name: rdb_mssql
    #image: ghcr.io/cynkra/dm:main
    image: r_mssql
    platform: linux/amd64
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - mssql-network
    volumes:
      - .:/root/workspace
    tty: true
    stdin_open: true
    # entrypoint: ["R"]
    entrypoint: ["R", "-e", "DBI::dbConnect(
                    odbc::odbc(),
                    driver = 'ODBC Driver 18 for SQL Server',
                    server = 'mssql',
                    database = 'test',
                    uid = 'SA',
                    pwd = 'YourStrong!Passw0rd',
                    port = 1433,
                    TrustServerCertificate = 'yes')"]

  # https://blog.logrocket.com/docker-sql-server/
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-RTM-ubuntu-20.04
    platform: linux/amd64
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    healthcheck:
      # test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "SELECT 1" -b -o /dev/null
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'test') BEGIN CREATE DATABASE test; END ELSE BEGIN SELECT 1; END;" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - mssql-db:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - mssql-network

# -- MYSQL SERVICE --
  rdb_mysql:
    container_name: rdb_mysql
    image: r_mssql
    platform: linux/amd64
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mysql-network
    volumes:
      - .:/root/workspace
    tty: true
    stdin_open: true
    # testing if connection works
    # entrypoint: ["R"]
    entrypoint: ["R", "-e", 'DBI::dbConnect(
                                  RMariaDB::MariaDB(),
                                  host = "mysql",
                                  username = "compose",
                                  password = "YourStrong!Passw0rd",
                                  dbname = "test")']

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "YourStrong!Passw0rd"
      MYSQL_DATABASE: test
      MYSQL_USER: compose
      MYSQL_PASSWORD: "YourStrong!Passw0rd"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pYourStrong!Passw0rd"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "3307:3306"
    networks:
      - mysql-network

# -- MARIA SERVICE --

  rdb_maria:
    container_name: rdb_maria
    image: r_mssql
    platform: linux/amd64
    depends_on:
      maria:
        condition: service_healthy
    networks:
      - maria-network
    volumes:
      - .:/root/workspace
    tty: true
    stdin_open: true
    # testing if connection works
    # entrypoint: ["R"]
    entrypoint: ["R", "-e", 'DBI::dbConnect(
                                  RMariaDB::MariaDB(),
                                  host = "maria",
                                  username = "compose",
                                  password = "YourStrong!Passw0rd",
                                  dbname = "test")']

  maria:
    container_name: maria
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "YourStrong!Passw0rd"
      MARIADB_DATABASE: test
      MARIADB_USER: compose
      MARIADB_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - maria-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 5s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    networks:
      - maria-network

# -- POSTGRES SERVICE --


  rdb_postgres:
    container_name: rdb_postgres
    image: r_postgres
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network
    volumes:
      - .:/root/workspace
    tty: true
    stdin_open: true
    # testing if connection works
    # entrypoint: ["R"]
    entrypoint: ["R", "-e", "DBI::dbConnect(
                    RPostgres::Postgres(),
                    host = 'postgres',
                    user = 'compose',
                    password = 'YourStrong!Passw0rd')"]

  # https://geshan.com.np/blog/2021/12/docker-postgres/
  postgres:
    container_name: postgres
    # FIXME: brittle tests fail with latest PostgreSQL
    image: postgres:14
    environment:
      POSTGRES_USER: compose
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network

# -- ORACLE SERVICE --

  rdb_oracle:
    container_name: rdb_oracle
    image: ghcr.io/cynkra/dm:main
    # image: r_oracle #FIXME something is missing from pak::pak()
    platform: linux/amd64
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - oracle-network
    volumes:
      - .:/root/workspace
    tty: true
    stdin_open: true
    # testing if connection works
    #entrypoint: ["R"]
    entrypoint: ["R", "-e", "DBI::dbConnect(odbc::odbc(),
               UID='compose',
               PWD='password1',
               Driver = 'OracleODBC-19c')"]

  #https://www.oracle.com/database/technologies/oracle-database-software-downloads.html#db_free
  #entreprise version requires access and license
  oracle:
    image: container-registry.oracle.com/database/free:latest
    #command: ["/bin/bash", "-c", "/oracle_init.sh"]
    container_name: oracle
    ports:
      - "1521:1521"
    networks:
      - oracle-network
    healthcheck:
      test: ["CMD-SHELL", "cat /sql/init.sql | sqlplus -S SYS/Oradoc_db1 AS SYSDBA"]
      interval: 30s
      timeout: 3s
      retries: 2
      start_period: 30s
    volumes:
      - oracle-db:/opt/oracle/oradata
      - ./r_images/r_oracle/init.sql:/sql/init.sql
