
version: '3'
volumes:
  oracle-db-xe:
    driver: local

networks:
  oracle-network-xe:
    driver: bridge

services:
  #Oracle Database Express Edition
  oracle-xe:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-xe
    ports:
      - "1521:1521"
    networks:
      - oracle-network-xe
    healthcheck:
      test: ["CMD-SHELL", "cat /sql/init.sql | sqlplus -S SYS/Oradoc_db1 AS SYSDBA"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - oracle-db-xe:/opt/oracle/oradata
      - ./init.sql:/sql/init.sql
