
version: '3'
volumes:
  maria-db:
    driver: local

networks:
  maria-network:
    driver: bridge

services:

# -- MARIA SERVICE --

  rdb_maria:
    container_name: rdb_maria
    image: r_mssql
    platform: linux/amd64
    depends_on:
      maria:
        condition: service_healthy
    networks:
      - maria-network
    volumes:
      - .:/root/workspace
    tty: true
    stdin_open: true
    # testing if connection works
    # entrypoint: ["R"]
    entrypoint: ["R", "-e", 'DBI::dbConnect(
                                  RMariaDB::MariaDB(),
                                  host = "maria",
                                  username = "compose",
                                  password = "YourStrong!Passw0rd",
                                  dbname = "test")']

  maria:
    container_name: maria
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "YourStrong!Passw0rd"
      MARIADB_DATABASE: test
      MARIADB_USER: compose
      MARIADB_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - maria-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 5s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    networks:
      - maria-network
