
version: '3'

include:
  - docker-compose.db-postgres.yml

services:

# -- POSTGRES SERVICE --

  rdb_postgres_test:
    container_name: rdb_postgres_test
    image: ghcr.io/krlmlr/rdb/r-postgres
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=compose
      - PGPASSWORD=YourStrong!Passw0rd
    tty: true
    stdin_open: true
    volumes:
      # simple test
      - ./test/test-postgres.R:/root/workspace/test.R
    entrypoint: ["Rscript", "/root/workspace/test.R"]

  rdb_postgres:
    container_name: rdb_postgres
    image: ghcr.io/krlmlr/rdb/r-postgres
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=compose
      - PGPASSWORD=YourStrong!Passw0rd
    tty: true
    stdin_open: true
    volumes:
      - ../r-dbi/RPostgres/:/root/workspace/
    entrypoint: ["R"]
