version: '3'
volumes:
  mssql-db:
    driver: local

networks:
  mssql-network:
    driver: bridge

services:
  # https://blog.logrocket.com/docker-sql-server/
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-RTM-ubuntu-20.04
    platform: linux/amd64
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    healthcheck:
      # test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "SELECT 1" -b -o /dev/null
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'test') BEGIN CREATE DATABASE test; END ELSE BEGIN SELECT 1; END;" -b -o /dev/null
      start_period: 4s
      interval: 0.2s
      timeout: 5s
      retries: 100
    volumes:
      - mssql-db:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - mssql-network
