
version: '3'
volumes:
  maria-db:
    driver: local

networks:
  maria-network:
    driver: bridge

services:

# -- MARIA SERVICE --

  rdb_maria:
    container_name: rdb_maria
    image: ghcr.io/krlmlr/rdb/r-mssql
    platform: linux/amd64
    depends_on:
      maria:
        condition: service_healthy
    networks:
      - maria-network
    tty: true
    stdin_open: true
    volumes:
      # simple test
      - ./test/test-maria.R:/root/workspace/.Rprofile
    entrypoint: ["R"]

  maria:
    container_name: maria
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "YourStrong!Passw0rd"
      MARIADB_DATABASE: test
      MARIADB_USER: compose
      MARIADB_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - maria-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 4s
      start_interval: 1s
      interval: 0.2s
      timeout: 5s
      retries: 100
    ports:
      - "3306:3306"
    networks:
      - maria-network
