
version: '3'

networks:
  mysql-network:
    driver: bridge

services:

# -- MYSQL SERVICE --
  rdb_mysql:
    container_name: rdb_mysql
    image: ghcr.io/krlmlr/rdb/r-mssql
    platform: linux/amd64
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mysql-network
    tty: true
    stdin_open: true
    volumes:
      # simple test
      - ./test/test-mysql.R:/root/workspace/.Rprofile
    entrypoint: ["R"]

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "YourStrong!Passw0rd"
      MYSQL_DATABASE: test
      MYSQL_USER: compose
      MYSQL_PASSWORD: "YourStrong!Passw0rd"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pYourStrong!Passw0rd"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "3307:3306"
    networks:
      - mysql-network
