version: '3'

include:
- docker-compose.db-mssql.yml

services:

# -- MSSQL SERVICE --
  rdb_mssql_test:
    container_name: rdb_mssql
    image: ghcr.io/krlmlr/rdb/r-mssql
    platform: linux/amd64
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - mssql-network
    tty: true
    stdin_open: true
    volumes:
      # simple test
      - ./test/test-mssql.R:/root/workspace/test.R
    entrypoint: ["Rscript", "/root/workspace/test.R"]
