
version: '3'
volumes:
  sqlite-db:
    driver: local

services:

# -- SQLITE SERVICE --

  rdb_sqlite:
    container_name: rdb_sqlite
    image: ghcr.io/krlmlr/rdb/r-sqlite
    platform: linux/amd64
    # depends_on:
    #   - sqlite
    tty: true
    stdin_open: true
    volumes:
      # simple test
      - ./test/test-sqlite.R:/root/workspace/.Rprofile
    entrypoint: ["R"]

  # sqlite:
  #   container_name: sqlite
  #   #https://github.com/KEINOS/Dockerfile_of_SQLite3 - built weekly
  #   image: keinos/sqlite3:latest
  #   volumes:
  #     - ./data:/data
  #   working_dir: /data
  #   command: sqlite3
  #   stdin_open: true
  #   tty: true

