
version: '3'

include:
- docker-compose.db-oracle.yml

services:

# -- ORACLE SERVICE --

  rdb_oracle:
    container_name: rdb_oracle
    image: ghcr.io/krlmlr/rdb/r-oracle
    platform: linux/amd64
    tty: true
    stdin_open: true
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - oracle-network
    volumes:
      # simple test
      - ./test/test-oracle.R:/root/workspace/.Rprofile
    entrypoint: ["R"]
