
version: '3'
volumes:
  oracle-db:
    driver: local

networks:
  oracle-network:
    driver: bridge

services:
  #https://www.oracle.com/database/technologies/oracle-database-software-downloads.html#db_free
  #entreprise version requires access and license
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    ports:
      - "1521:1521"
    networks:
      - oracle-network
    healthcheck:
      test: ["CMD-SHELL", "cat /sql/init.sql | sqlplus -S SYS/Oradoc_db1 AS SYSDBA"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - oracle-db:/opt/oracle/oradata
      - ./init.sql:/sql/init.sql
