
version: '3'
volumes:
  postgres-db:
    driver: local

networks:
  postgres-network:
    driver: bridge

services:

# -- POSTGRES SERVICE --

  rdb_postgres_test:
    container_name: rdb_postgres_test
    image: ghcr.io/krlmlr/rdb/r-postgres
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network
    tty: true
    stdin_open: true
    volumes:
      # simple test
      - ./test/test-postgres.R:/root/workspace/test.R
    entrypoint: ["Rscript", "/root/workspace/test.R"]

  rdb_postgres:
    container_name: rdb_postgres
    image: ghcr.io/krlmlr/rdb/r-postgres
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network
    tty: true
    stdin_open: true
    volumes:
      - ../r-dbi/RPostgres/:/root/workspace/
    entrypoint: ["R"]

  # https://geshan.com.np/blog/2021/12/docker-postgres/
  postgres:
    container_name: postgres
    # FIXME: brittle tests fail with latest PostgreSQL
    image: postgres:14
    environment:
      POSTGRES_USER: compose
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 4s
      start_interval: 1s
      interval: 0.2s
      timeout: 5s
      retries: 100
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network
