
version: '3'
volumes:
  sqlite-db:
    driver: local

services:

# -- SQLITE SERVICE --

  rdb_sqlite:
    container_name: rdb_sqlite
    image: ghcr.io/krlmlr/rdb/r-sqlite
    platform: linux/amd64
    # depends_on:
    #   - sqlite
    tty: true
    stdin_open: true
    volumes:
      # simple test
      - ./test/test-sqlite.R:/root/workspace/.Rprofile
    entrypoint: ["R"]
